# Generated by Django 4.2 on 2023-11-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_user_book_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='date_entry',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='date_exit',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='room_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
