# Generated by Django 4.2 on 2023-11-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_bookingroom_first_name_bookingroom_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book_room',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='user',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='date_entry',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='date_exit',
            field=models.CharField(max_length=15),
        ),
    ]
