# Generated by Django 4.2 on 2023-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count_rooms', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('child_place', models.BooleanField(default=False)),
                ('price_pn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='rooms_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('booked_now', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviewers_photos')),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
