# Generated by Django 4.2 on 2023-11-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_service',
            new_name='AdditionalService',
        ),
    ]
