# Generated by Django 4.2 on 2023-11-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0002_rename_additional_service_additionalservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalService',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
